export const statRangeByPosition: Record<string, Record<string, [number, number]>> = {
	setter: {
		jumping: [50, 70],
		passing: [60, 80],
		power: [40, 60],
		consistency: [60, 85],
		setting: [75, 90],
		blocking: [40, 60],
		stamina: [60, 80],
	},
	hitter: {
		jumping: [65, 85],
		passing: [45, 65],
		power: [65, 85],
		consistency: [60, 80],
		setting: [35, 55],
		blocking: [65, 85],
		stamina: [60, 80],
	},
	middle: {
		jumping: [75, 90],
		passing: [35, 55],
		power: [65, 80],
		consistency: [55, 75],
		setting: [35, 55],
		blocking: [75, 90],
		stamina: [60, 80],
	},
	libero: {
		jumping: [30, 50],
		passing: [75, 90],
		power: [30, 50],
		consistency: [70, 90],
		setting: [55, 75],
		blocking: [10, 30],
		stamina: [70, 90],
	}
};
  

export const teamNames = [
	"Spike Syndicate",
	"Net Ninjas",
	"Block Party",
	"Ace Assassins",
	"Kill Shot",
	"Smash Titans",
	"The Dig Force",
	"Vertical Threat",
	"Powerline",
	"Cross Court Kings",
	"Set to Stun",
	"Net Results",
	"Bumpin' Uglies",
	"Hit Me Baby One More Time",
	"Notorious D.I.G.",
	"New Kids on the Block",
	"I'd Hit That",
	"Served Cold",
	"Spikological Warfare",
	"Dig-a-saurus Rex",
	"Sunset Spikers",
	"Coastal Chaos",
	"Northern Netters",
	"Midtown Smash",
	"Downtown Diggers",
	"Pacific Power",
	"Urban Elevation",
	"Highland Heat",
	"Lakeside Killers",
	"Metro Volley Club"
]

export const firstNames = [
	"Matt",
	"Ozzmatazz",
	"Contessa",
	"Brynn",
	"Reilly",
	"Terrence",
	"Cornstock",
	"Billy Joe",
	"Marissa",
	"Kayleigh",
	"Botswana",
	"Karminissa",
	"Jazz",
	"Beatrice",
	"Grace",
	"Sara",
	"Clarrisa",
	"Rodney",
	"Cara",
	"Darth",
	"Garth",
	"Saxon",
	"John",
	"Jacob",
	"Crysanthemum",
	"Coraline",
	"Beau",
	"Terrence",
	"Nick",
	"Asher",
	"Tomás",
	"Quentin",
	"Philip",
	"Draco",
	"Dumbledore",
	"Hubert",
	"Juan",
	"Josefina",
	"David",
	"Corinne",
	"Marcos",
	"Maria", 
	"Marty",
	"Alicia",
	"Julia",
	"Olivia",
	"Teresa",
	"Daniel",
	"Quentin",
	"Seamus"
];

export const lastNames = [
	"O'Malley",
	"Johnson",
	"Cellars",
	"Matthews",
	"Gingleheimer-Smith",
	"Dinklestein",
	"Williams",
	"McTabernathy",
	"Doorfenshmith",
	"Goldstein",
	"Hoovensmitch",
	"Briddleby",
	"Borker",
	"Haverford",
	"Flagg",
	"Jordan",
	"Lively",
	"Reynolds",
	"Mungo",
	"Congolius",
	"Giggums",
	"Pinklewerry",
	"Persifermus",
	"John",
	"Lichtenstein",
	"Townley",
	"Tuttle",
	"Raytheon",
	"Erasmus",
	"Hollander",
	"Adams",
	"Maloise",
	"Concão",
	"Felicitão",
	"Jones",
	"Ng",
	"Chen",
	"Huang"
]